### ISSUE TITLE
[SITE BUG] Map displaying wrong freq

### ISSUE THREAD

**Issue by Scorcher-2** [vatACARS/plugin#136]
**Bug Description**
The coverage map is displaying wrong freq in the vhf field

**Expected behaviour**
Show correct freq.

**Screenshots**
![image](https://github.com/user-attachments/assets/1b5a1a34-e7f9-4e70-9cfb-b18b08614cc1)

**Desktop Environment (please complete the following information):**
 - OS: Windows

**Submitted from school laptop so sorry @PlutonusDev **

**Comment by Scorcher-2** [comment]
(the .325 aint showing)

**Comment by PlutonusDev** [comment]
https://GitHub.com/vatACARS/site

**Comment by Scorcher-2** [comment]
josh i cant access that its private😢

**Comment by PlutonusDev** [comment]
Fixed and deployed.
