### ISSUE TITLE
[BUG] CTD when retrieving PDC at NZAA

### ISSUE THREAD

**Issue by zkaviator** [vatACARS/plugin#170]
**Bug Description**
When connected under PDC NZAA, whenever a pilot sends a PDC request, when relayed via Hoppies, vatSys crashes to desktop

**Reproduction Steps**
1. Connect with PDC NZAA inside vatAcars as normal
2. Crash occurs when a pilot sends a PDC request

**Expected behaviour**
Expected behaviour is a notification to come with the message of the PDC request and ability to action by responding to the PDC.

**Desktop Environment (please complete the following information):**
 - OS: Windows 10
 - Plugin Version: 1.1.2

**Additional context**
Crash reports: 

Application: vatSys.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at vatACARS.Properties.Settings.get_p_pdc()
   at vatACARS.Helpers.Transceiver.addTelexMessage(TelexMessage)
   at vatACARS.Util.HoppiesInterface+<PollTimer>d__14.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Faulting application name: vatSys.exe, version: 0.4.8984.39897, time stamp: 0x66b21292
Faulting module name: KERNELBASE.dll, version: 10.0.19041.5007, time stamp: 0x0943bdcd
Exception code: 0xe0434352
Fault offset: 0x001410a2
Faulting process ID: 0x1274
Faulting application start time: 0x01db1d3b0ff91e80
Faulting application path: D:\vatSys\bin\vatSys.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 272c80fe-2620-4852-b890-71f335867d14
Faulting package full name:
Faulting package-relative application ID: 

Fault bucket 1968694699139113095, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: vatSys.exe
P2: 0.4.8984.39897
P3: 66b21292
P4: vatACARS
P5: 1.0.0.0
P6: ae804a42
P7: d2
P8: 0
P9: System.NullReferenceException
P10:

The following ACARS message was registered on Hoppies that looked like this that ended up causing the crash: <br><br></div>
Network  VATSIM
From | ANZ902 | Received | 2024-10-13 06:41Z
To | NZAA | Relayed | 2024-10-13 06:41Z
Type | telex

REQUEST PREDEP CLEARANCE
ANZ902 A320 TO NTAA
AT NZAA STAND 15
ATIS N

**Comment by AussieScorcher** [comment]
Hi there this is a known issue that is caused when you don't have any profile installed unfortunately I can't fix the issue internally however you can fix it by following these instructions:

Please download the zip linked below and place extracted files in the following directory: ```%localappdata%/vatACARS/profiles```

[Eurocat_Australia.zip](https://github.com/user-attachments/files/17356855/Eurocat_Australia.zip)

 *You can paste the path at the top of your file explorer. If the folder doesn't exist, please start the plugin with the latest version at least once first.*

This should fix the plugin for you. I appreciate your understanding.
