### ISSUE TITLE
[BUG] Graphical issue with editor window after sending a message.

### ISSUE THREAD

**Issue by ScorcherPlays** [vatACARS/plugin#33]
**Bug Description**
The green text/button remains visible when reopening the editor window after sending a message

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Go to the Editor window and send a message
2. Reopen the window with a different message.

**Expected behaviour**
Should refresh drawn graphics after reopening.

**Screenshots**
![image](https://github.com/vatACARS/plugin/assets/67866285/007f5c50-e965-45d2-aabb-60a7044ee4dd)

**Desktop Environment (please complete the following information):**
 - OS: Windows

**Comment by PlutonusDev** [comment]
This was inadvertently fixed somewhere during other development.
