### ISSUE TITLE
[BUG] Connected stations not appearing after connecting

### ISSUE THREAD

**Issue by ScorcherPlays** [vatACARS/plugin#34]
**Bug Description**
After accepting a logon the callsign doesn't not show up in the connected list.

**Reproduction Steps**
Steps to reproduce the behaviour:
1. Accept a logon
2. See the issue.

**Expected behaviour**
The callsign should show up in the connected station's list and allow for logoff and transferring the pilot between ATSU's

**Screenshots**
![image](https://github.com/vatACARS/plugin/assets/67866285/81b9655d-6d7d-45f4-a653-b5949d13aee0)

**Desktop Environment (please complete the following information):**
 - OS: Windows

**Comment by PlutonusDev** [comment]
Resolved
