### ISSUE TITLE
[REQUEST] Add scaling to dispatch window

### ISSUE THREAD

**Issue by KINGKOBER** [vatACARS/plugin#49]
**Problem Description**
The issue is some people have smaller monitors so being able to make it bigger or smaller would help allot.

**Proposed Solution**
make it so we can make it bigger and smaller.

**Comment by PlutonusDev** [comment]
This will require changes to the way we paint the information displayed in the dispatch window. This is accepted but will be marked as a low priority until at least the 1.0 release.
