### ISSUE TITLE
[REQUEST] Profile selector or Profile detector

### ISSUE THREAD

**Issue by Verbjimtim** [vatACARS/plugin#68]
The ability to either manually select a "profile" which works for different FIRs. eg, Australian domestic phraseology, Australian Oceanic phraseology (simplified domestic) North Atlantic track phraseology, US, NZ, etc.

The detector maybe having the plugin look for a specific folder in the profile loaded so FIRs can update their phraseology as required.

**Comment by PlutonusDev** [comment]
This is in the pipeline, though currently not expected to be ready for the 1.0 release.
