### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Madracus** [vatACARS/plugin#71]
**Bug Description**
When it wanted me to select the vatsys exe I accedently pressed the  vatacars application any way to change it and to install it.
**Reproduction Steps**
I reenstaled the application
**Expected behaviour**
To be able to change the directory to my vatsys client 

**Screenshots**
![ISSUE](https://github.com/vatACARS/plugin/assets/149668345/661c3d81-678e-4ebb-a192-9cd6a505a3c6)

**Desktop Environment (please complete the following information):**
Windows 11
1.0.1

**Additional context**
Any other information about the problem can be provided here.

**Comment by PlutonusDev** [comment]
This was an oversight by me, will be patched in the next release of the hub. Cheers
